services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
      - database
    env_file:
      - .env.local

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - .env.local
